// ui/src/components/ui/separator.tsx
"use client";

import { Separator as SeparatorPrimitive } from "@base-ui/react/separator";

import { cn } from "@/lib/utils";

function Separator({ className, orientation = "horizontal", ...props }: SeparatorPrimitive.Props) {
    return (
        <SeparatorPrimitive
            data-slot="separator"
            orientation={orientation}
            className={cn(
                "shrink-0 bg-border data-horizontal:h-px data-horizontal:w-full data-vertical:w-px data-vertical:self-stretch",
                className,
            )}
            {...props}
        />
    );
}

export { Separator };

// web/src/lib/components/ui/separator/separator.svelte
<script lang="ts">
import { cn } from "$lib/utils.js";
import type { Separator as SeparatorPrimitive } from "bits-ui";

type $$Props = SeparatorPrimitive.Props;

const className: $$Props["class"] = undefined;
export const orientation: $$Props["orientation"] = "horizontal";
export const decorative: $$Props["decorative"] = undefined;
export { className as class };
</script>

<SeparatorPrimitive.Root
	class={cn(
		"shrink-0 bg-border",
		orientation === "horizontal" ? "h-[1px] w-full" : "h-full w-[1px]",
		className
	)}
	{orientation}
	{decorative}
	{...$$restProps}
/>
