// web/src/app.svelte
<script lang="ts">
    import { setContext } from "svelte";
    import { createConfigState } from "./lib/api.svelte";
    import { createEditorsState } from "./state/editors.svelte";
    import { createUIState } from "./state/ui.svelte";
    import Menubar from "./ui/menubar.svelte";
    import FileMenu from "./ui/menus/file.svelte";
    import OptionsMenu from "./ui/menus/options.svelte";
    import ViewMenu from "./ui/menus/view.svelte";
    import FontMenu from "./ui/menus/font.svelte";
    import LanguageMenu from "./ui/menus/language.svelte";
    import ExamplesMenu from "./ui/menus/examples.svelte";
    import HelpMenu from "./ui/menus/help.svelte";
    import Container from "./ui/container.svelte";
    import Footer from "./ui/footer.svelte";
    import GoContainer from "./ui/go.svelte";
    import JSONContainer from "./ui/json.svelte";
    import {createMessageState} from "./state/message.svelte";
    import {Events} from "@wailsio/runtime";
    import {type WailsEvent} from "@wailsio/runtime/types/events";

    const config = createConfigState();
    const ui = createUIState();

    let goElement: HTMLElement;
    let jsonElement: HTMLElement;

    const editors = createEditorsState({
        language: config.locale,
        fontSize: config.fontSize,
        goElement: goElement,
        jsonElement: jsonElement,
    });
    const message = createMessageState()

    setContext("config", config);
    setContext("ui", ui);
    setContext("editors", editors);
    setContext("message", message);

   $effect(() => {
        config.init();
        editors.init();


       document.defaultView?.addEventListener("resize", () => {
            editors.jsonEditor?.layout();
            editors.goEditor?.layout();

            Events.Emit(new WailsEvent("resize"));
        });

       Events.On("error", (msg: string) => {
            message.message = msg;
        });
    });

    $effect(() => {
        if (config.locale) {
            editors.init();
        }
    });

    $effect(() =>{
        if (config.fontSize) {
            editors.jsonEditor?.updateOptions({ fontSize: value });
            editors.goEditor?.updateOptions({ fontSize: value });
        }
    })

    $effect(() => {
        if (editors.jsonEditor) {
            editors.jsonEditor.getModel()?.onDidChangeContent(() => {
                if (config.realTime) {
                    editors.json2go();
                }
            });
        }
    })
</script>

<main class="w-screen h-screen flex flex-col">
    <Menubar>
        <FileMenu />
        <OptionsMenu />
        <ViewMenu />
        <FontMenu />
        <LanguageMenu />
        <ExamplesMenu />
        <HelpMenu />
    </Menubar>
    <Container>
        <JSONContainer bind:goElement />
        <GoContainer bind:jsonElement/>
    </Container>
    <Footer />
</main>

// ui/src/app.tsx
import { useConfigStore } from "@/lib/api.ts";
import { useEditorsStore } from "@/store/editors.ts";
import { useMessageStore } from "@/store/message.ts";
import Container from "@/ui/container.tsx";
import Footer from "@/ui/footer.tsx";
import GoContainer from "@/ui/go.tsx";
import JSONContainer from "@/ui/json.tsx";
import Menubar from "@/ui/menubar.tsx";
import ExamplesMenu from "@/ui/menus/examples.tsx";
import FileMenu from "@/ui/menus/file.tsx";
import FontMenu from "@/ui/menus/font.tsx";
import HelpMenu from "@/ui/menus/help.tsx";
import LanguageMenu from "@/ui/menus/language.tsx";
import OptionsMenu from "@/ui/menus/options.tsx";
import ViewMenu from "@/ui/menus/view.tsx";
import { useEffect, useRef } from "react";
import "./app.css";
import { Events } from "@wailsio/runtime";

function App() {
    const fontSize = useConfigStore((s) => s.fontSize);
    const language = useConfigStore((s) => s.language);
    const realTime = useConfigStore((s) => s.realTime);
    const initConfig = useConfigStore((s) => s.init);

    const setMessage = useMessageStore((state) => state.setMessage);

    const init = useRef(false);

    const { jsonEditor, goEditor, init: initEditors, generate } = useEditorsStore();

    const realTimeRef = useRef(realTime);
    realTimeRef.current = realTime;
    const generateRef = useRef(generate);
    generateRef.current = generate;

    useEffect(() => {
        void initConfig();

        document.defaultView?.addEventListener("resize", () => {
            jsonEditor?.layout();
            goEditor?.layout();
            void Events.Emit("resize");
        });

        Events.On("error", (ev) => setMessage(ev.data));

        init.current = true;
    }, []);

    useEffect(() => {
        if (language) {
            initEditors(language, fontSize, "json-editor", "go-editor");
        }
    }, [language]);

    useEffect(() => {
        if (init.current) {
            jsonEditor?.updateOptions({ fontSize });
            goEditor?.updateOptions({ fontSize });
        }
    }, [fontSize]);

    useEffect(() => {
        if (jsonEditor) {
            jsonEditor.getModel()?.onDidChangeContent(() => {
                if (realTimeRef.current) {
                    generateRef.current();
                }
            });
        }
    }, [jsonEditor]);

    return (
        <main className="w-screen h-screen flex flex-col">
            <Menubar>
                <FileMenu />
                <OptionsMenu />
                <ViewMenu />
                <FontMenu />
                <LanguageMenu />
                <ExamplesMenu />
                <HelpMenu />
            </Menubar>
            <Container>
                <JSONContainer />
                <GoContainer />
            </Container>
            <Footer />
        </main>
    );
}

export default App;
