// web/src/ui/go.svelte
<script lang="ts">
    import { getContext } from "svelte";
    import { _ } from "svelte-i18n";
    import type { UIState } from "../state/ui.svelte";
    import type { EditorsState } from "../state/editors.svelte";

    const ui = getContext<UIState>("ui");
    const editors = getContext<EditorsState>("editors");

    function copyGo() {
        editors.copyFromGoEditor();
    }
</script>

<div
    id="container-go"
    style="display: {ui.view === 'JSON Only' ? 'none' : ''}"
    class="group {ui.layout === 'Two Columns' && ui.view === 'Go Only' ? 'col-span-2' : ''} {ui.layout === 'Two Rows' && ui.view === 'Go Only' ? 'row-span-2' : ''} {ui.layout === 'Two Columns' && ui.view === 'JSON and Go' ? 'border-l' : ''} {ui.layout === 'Two Rows' && ui.view === 'JSON and Go' ? 'border-t' : ''}"
>
    <div class="w-full bg-white/50 flex flex-row">
        <span class="py-1 px-4 select-none text-purple-700 font-mono group-focus-within:text-purple-500">
            Go
        </span>
        <button type="button" on:click={copyGo}>
            {$_("Copy")}
        </button>
    </div>
    <div class="w-full h-32 grow" id="go-editor"></div>
</div>

// app/ui/src/ui/go.tsx
import { cn } from "@/lib/utils.ts";
import { useEditorsStore } from "@/store/editors.ts";
import { Layout, useLayoutStore } from "@/store/layout.ts";
import { View, useViewStore } from "@/store/view.ts";
import { useTranslation } from "react-i18next";

export default function () {
	const { t } = useTranslation();
	const layout = useLayoutStore((state) => state.layout);
	const view = useViewStore((state) => state.view);
	const copyGo = useEditorsStore((state) => state.copyGo);

	return (
		<div
			id="container-go"
			style={{ display: view === View.JSONOnly ? "none" : "" }}
			className={cn("group", {
				"col-span-2": layout === Layout.TwoColumns && view === View.GoOnly,
				"row-span-2": layout === Layout.TwoRows && view === View.GoOnly,
				"border-l": layout === Layout.TwoColumns && view === View.JSONAndGo,
				"border-t": layout === Layout.TwoRows && view === View.JSONAndGo,
			})}
		>
			<div className="w-full bg-white/50 flex flex-row">
				<span className="py-1 px-4 select-none text-purple-700 font-mono group-focus-within:text-purple-500">
					Go
				</span>
				<button onClick={copyGo}>{t("Copy")}</button>
			</div>
			<div className="w-full h-32 grow" id="go-editor"></div>
		</div>
	);
}
