// web/src/ui/json.svelte
<script lang="ts">
    import { getContext } from "svelte";
    import { _ } from "svelte-i18n";
    import type { UIState } from "../state/ui.svelte";
    import type { EditorsState } from "../state/editors.svelte";

    const ui = getContext<UIState>("ui");
    const editors = getContext<EditorsState>("editors");

    function pasteJSON() {
        editors.pasteToJSONEditor();
    }
</script>

<div
    id="container-json"
    style="display: {ui.view === 'Go Only' ? 'none' : ''}"
    class="group {ui.layout === 'Two Columns' && ui.view === 'JSON Only' ? 'col-span-2' : ''} {ui.layout === 'Two Rows' && ui.view === 'JSON Only' ? 'row-span-2' : ''}"
>
    <div class="w-full bg-white/50 flex flex-row">
        <span class="py-1 px-4 select-none text-yellow-700 font-mono group-focus-within:text-yellow-500">
            JSON
        </span>
        <button type="button" on:click={pasteJSON}>
            {$_("Paste")}
        </button>
    </div>
    <div class="w-full h-32 grow" id="json-editor"></div>
</div>

// app/ui/src/ui/json.tsx
import {cn} from "@/lib/utils.ts"
import {useTranslation} from "react-i18next"
import {Layout, useLayoutStore} from "@/store/layout.ts"
import {useViewStore, View} from "@/store/view.ts"
import {useEditorsStore} from "@/store/editors.ts"

export default function () {
    const {t} = useTranslation()
    const layout = useLayoutStore(state => state.layout)
    const view = useViewStore(state => state.view)
    const pasteJSON = useEditorsStore(state => state.pasteJSON)

    return (
        <div id="container-json" style={{display: view === View.GoOnly ? "none" : ""}}
             className={cn("group", {
                 "col-span-2": layout === Layout.TwoColumns && view === View.JSONOnly,
                 "row-span-2": layout === Layout.TwoRows && view === View.JSONOnly,
             })}>
            <div className="w-full bg-white/50 flex flex-row">
                <span className="py-1 px-4 select-none text-yellow-700 font-mono group-focus-within:text-yellow-500">
                    JSON
                </span>
                <button onClick={pasteJSON}>{t("Paste")}</button>
            </div>
            <div className="w-full h-32 grow" id="json-editor"></div>
        </div>
    )
}
