// web/src/ui/menubar.svelte
<script lang="ts">
    import { getContext } from "svelte";
    import { Dialog } from "bits-ui";
    import { Menubar } from "bits-ui";
    import type { DialogState } from "../state/dialog.svelte";

    const dialog = getContext<DialogState>("dialog");
</script>

<Dialog>
    <Menubar class="rounded-none border-none bg-transparent">
        <slot></slot>
    </Menubar>
    {#if dialog}
        {dialog}
    {/if}
</Dialog>

// app/ui/src/ui/menubar.tsx
import { Dialog } from "@/components/ui/dialog.tsx";
import { Menubar } from "@/components/ui/menubar.tsx";
import { useDialogStore } from "@/store/dialog.ts";
import { PropsWithChildren } from "react";

export default function ({ children }: PropsWithChildren) {
	const dialog = useDialogStore((state) => state.dialog);

	return (
		<Dialog>
			<Menubar className="rounded-none border-none bg-transparent">
				{children}
			</Menubar>
			{dialog}
		</Dialog>
	);
}
