// app/ui/src/ui/about.tsx
import {DialogClose, DialogContent, DialogFooter, DialogHeader, DialogTitle,} from "@/components/ui/dialog.tsx"
import {Button} from "@/components/ui/button.tsx"
import {useEffect, useState} from "react"
import {GetVersion} from "../../wailsjs/go/main/App"
import {useTranslation} from "react-i18next"

export default function () {
    const {t} = useTranslation()

    const [version, setVersion] = useState("")
    useEffect(() => {
        GetVersion().then(value => setVersion(value))
    }, [])

    return (
        <DialogContent className="select-none">
            <DialogHeader>
                <DialogTitle>{t("about.title", "About")}</DialogTitle>
            </DialogHeader>
            <div className="flex flex-col space-y-2 items-center justify-center text-gray-900">
                <p className="text-lg font-semibold">json2go</p>
                <p className="leading-relaxed">{t("about.description", "Generate Go type definitions from JSON")}</p>
                <div className="leading-relaxed">
                    <p><span className="font-semibold select-none">{t("about.license", "License: ")}</span>MIT</p>
                    <p><span className="font-semibold select-none">{t("about.version", "Version: ")}</span>{version}</p>
                </div>
                <p>Copyright © 2022 fhluo</p>
            </div>
            <DialogFooter>
                <DialogClose asChild>
                    <Button variant="secondary">{t("OK")}</Button>
                </DialogClose>
            </DialogFooter>
        </DialogContent>
    )
}

// json2go-web/src/ui/dialogs/about.svelte
<script lang="ts">
    import {getContext} from "svelte";
    import {type ConfigState, openHomePage} from "$lib/api.svelte";
    import {_} from "svelte-i18n"
    import {DialogContent, DialogFooter, DialogHeader, DialogTitle} from "$lib/components/ui/dialog";
    import {Tooltip, TooltipContent, TooltipTrigger} from "$lib/components/ui/tooltip";
    import {Button} from "$lib/components/ui/button";

    let config = getContext<ConfigState>("config")
</script>

<DialogContent class="select-none">
    <DialogHeader>
        <DialogTitle>{$_("about.title", {default: "About"})}</DialogTitle>
    </DialogHeader>
    <div class="flex flex-col items-center justify-center space-y-2 text-gray-900">
        <Tooltip>
            <TooltipTrigger asChild>
                <p class="text-lg font-semibold" ondblclick={openHomePage}>
                    json2go
                </p>
            </TooltipTrigger>
            <TooltipContent class="bg-transparent text-slate-600">
                <p>
                    {$_("about.tip", {default: "Double-click to visit json2go on Github.com"})}
                </p>
            </TooltipContent>
        </Tooltip>
        <p class="text-sm leading-relaxed text-muted-foreground">
            {$_("about.description", {default: "Generate Go type definitions from JSON"})}
        </p>
        <div class="leading-relaxed text-sm">
            <p>
                <span class="select-none">
                    {$_("about.license", {default: "License: "})}
                </span>
                MIT
            </p>
            <p>
                <span class="select-none">
                    {$_("about.version", {default: "Version: "})}
                </span>
                {config.version}
            </p>
        </div>
        <p class="text-sm">Copyright © 2022 fhluo</p>
    </div>
    <DialogFooter>
        <Button variant="secondary">{$_("OK")}</Button>
    </DialogFooter>
</DialogContent>
