// web/src/ui/menus/examples.svelte
<script lang="ts">
    import { getContext } from "svelte";
    import { GetExamples } from "../../../wailsjs/go/main/App";
    import { examples } from "../../../wailsjs/go/models";
    import { _ } from "svelte-i18n";
    import { Menubar } from "bits-ui";
    import type { EditorsState } from "../../state/editors.svelte";

    let exampleList: examples.Example[] = [];
    const editors = getContext<EditorsState>("editors");

    $effect(() => {
        GetExamples().then((examples) => {
            exampleList = examples;
        });
    });

    function setJSON(content: string) {
        editors.json = content;
    }
</script>

<Menubar.Menu>
    <Menubar.Trigger>{$_("examples.title", { default: "Examples" })}</Menubar.Trigger>
    <Menubar.Content>
        {#each exampleList as example}
            <Menubar.Item key={example.title} on:click={() => setJSON(example.content)}>
                {example.title}
            </Menubar.Item>
        {/each}
    </Menubar.Content>
</Menubar.Menu>

// app/ui/src/ui/menus/examples.tsx
import {
	MenubarContent,
	MenubarItem,
	MenubarMenu,
	MenubarTrigger,
} from "@/components/ui/menubar.tsx";
import { useEditorsStore } from "@/store/editors.ts";
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { GetExamples } from "../../../wailsjs/go/main/App";
import { examples } from "../../../wailsjs/go/models.ts";
import Example = examples.Example;

export default function () {
	const { t } = useTranslation();
	const setJSON = useEditorsStore((state) => state.setJSON);

	const [exampleList, setExampleList] = useState([] as Example[]);
	useEffect(() => {
		GetExamples().then((value) => {
			setExampleList(value);
		});
	}, []);

	return (
		<MenubarMenu>
			<MenubarTrigger>{t("examples.title", "Examples")}</MenubarTrigger>
			<MenubarContent>
				{exampleList.map((example) => (
					<MenubarItem
						key={example.title}
						onClick={() => setJSON(example.content)}
					>
						{example.title}
					</MenubarItem>
				))}
			</MenubarContent>
		</MenubarMenu>
	);
}
