// web/src/ui/menus/options.svelte
<script lang="ts">
    import { getContext } from "svelte";
    import { _ } from "svelte-i18n";
    import { Menubar } from "bits-ui";
    import type { ConfigState } from "src/lib/api.svelte";

    const config = getContext<ConfigState>("config");

    function toggleValidJSON() {
        config.validJSON = !config.validJSON;
    }

    function toggleRealTime() {
        config.realTime = !config.realTime;
    }
</script>

<Menubar.Menu>
    <Menubar.Trigger>{$_("options.title", { default: "Options" })}</Menubar.Trigger>
    <Menubar.Content>
        <Menubar.CheckboxItem checked={config.validJSON} on:checkedChange={toggleValidJSON}>
            {$_("options.valid", { default: "Validate JSON before generation" })}
        </Menubar.CheckboxItem>
        <Menubar.CheckboxItem checked={config.realTime} on:checkedChange={toggleRealTime}>
            {$_("options.realTime", { default: "Generate in real time" })}
        </Menubar.CheckboxItem>
    </Menubar.Content>
</Menubar.Menu>

// app/ui/src/ui/menus/options.tsx
import {
	MenubarCheckboxItem,
	MenubarContent,
	MenubarMenu,
	MenubarTrigger,
} from "@/components/ui/menubar.tsx";
import { useRealTimeStore, useValidJSONStore } from "@/lib/store.ts";
import { useTranslation } from "react-i18next";

export default function () {
	const { t } = useTranslation();
	const { validJSON, setValidJSON } = useValidJSONStore();
	const { realTime, setRealTime } = useRealTimeStore();

	return (
		<MenubarMenu>
			<MenubarTrigger>{t("options.title", "Options")}</MenubarTrigger>
			<MenubarContent>
				<MenubarCheckboxItem
					checked={validJSON}
					onCheckedChange={(checked) => setValidJSON(checked)}
				>
					{t("options.valid", "Validate JSON before generation")}
				</MenubarCheckboxItem>
				<MenubarCheckboxItem
					checked={realTime}
					onCheckedChange={(checked) => setRealTime(checked)}
				>
					{t("options.realTime", "Generate in real time")}
				</MenubarCheckboxItem>
			</MenubarContent>
		</MenubarMenu>
	);
}
