// app/ui/src/ui/menus/file.tsx
import {MenubarContent, MenubarItem, MenubarMenu, MenubarSeparator, MenubarTrigger} from "@/components/ui/menubar.tsx"
import {DialogTrigger} from "@/components/ui/dialog.tsx"
import Settings from "@/ui/dialogs/settings.tsx"
import {EventsEmit} from "../../../wailsjs/runtime"
import {useTranslation} from "react-i18next"
import {useEditorsStore} from "@/store/editors.ts"
import {useDialogStore} from "@/store/dialog.ts"

export default function () {
    const {t} = useTranslation()
    const setDialog = useDialogStore(state => state.setDialog)
    const {openJSON, saveGo} = useEditorsStore()

    return (
        <MenubarMenu>
            <MenubarTrigger>
                {t("file.title", "File")}
            </MenubarTrigger>
            <MenubarContent>
                <MenubarItem onClick={openJSON}>
                    {t("file.openJSON", "Open JSON file")}
                </MenubarItem>
                <MenubarItem onClick={saveGo}>
                    {t("file.saveGo", "Save Go source file")}
                </MenubarItem>
                <MenubarSeparator/>
                <DialogTrigger asChild>
                    <MenubarItem onClick={() => setDialog(<Settings/>)}>
                        {t("file.settings", "Settings")}
                    </MenubarItem>
                </DialogTrigger>
                <MenubarSeparator/>
                <MenubarItem onClick={() => EventsEmit("exit")}>
                    {t("file.exit", "Exit")}
                </MenubarItem>
            </MenubarContent>
        </MenubarMenu>
    )
}

// web/src/ui/menus/file.svelte
<script lang="ts">
    import {getContext} from "svelte";
    import {_} from "svelte-i18n";
    import {Menubar} from "bits-ui";
    import {EventsEmit} from "../../../wailsjs/runtime";
    import Settings from "@/ui/dialogs/settings.svelte";
    import type {EditorsState} from "../../state/editors.svelte";

    const editors = getContext<EditorsState>("editors");
</script>

<Menubar.Menu>
    <Menubar.Trigger>{$_("file.title", {default: "File"})}</Menubar.Trigger>
    <Menubar.Content>
        <Menubar.Item on:click={editors.openJSONFile}>
            {$_("file.openJSON", {default: "Open JSON file"})}
        </Menubar.Item>
        <Menubar.Item on:click={editors.saveGoFile}>
            {$_("file.saveGo", {default: "Save Go source file"})}
        </Menubar.Item>
        <Menubar.Separator/>
        <Menubar.Item on:click={()=> {
            // Open the settings dialog
         }}>
            {$_("file.settings", {default: "Settings"})}
        </Menubar.Item>
        <Menubar.Separator/>
        <Menubar.Item on:click={() => EventsEmit("exit")}>
            {$_("file.exit", {default: "Exit"})}
        </Menubar.Item>
    </Menubar.Content>
</Menubar.Menu>
