// app/ui/src/ui/menus/help.tsx
import { DialogTrigger } from "@/components/ui/dialog.tsx";
import {
	MenubarContent,
	MenubarItem,
	MenubarMenu,
	MenubarSeparator,
	MenubarTrigger,
} from "@/components/ui/menubar.tsx";
import { useDialogStore } from "@/store/dialog.ts";
import About from "@/ui/dialogs/about.tsx";
import Updates from "@/ui/dialogs/updates.tsx";
import { useTranslation } from "react-i18next";

export default function () {
	const { t } = useTranslation();
	const setDialog = useDialogStore((state) => state.setDialog);

	return (
		<MenubarMenu>
			<MenubarTrigger>{t("help.title", "Help")}</MenubarTrigger>
			<MenubarContent>
				<DialogTrigger asChild>
					<MenubarItem onClick={() => setDialog(<Updates />)}>
						{t("help.updates", "Check for updates")}
					</MenubarItem>
				</DialogTrigger>
				<MenubarSeparator />
				<DialogTrigger asChild>
					<MenubarItem onClick={() => setDialog(<About />)}>
						{t("help.about", "About")}
					</MenubarItem>
				</DialogTrigger>
			</MenubarContent>
		</MenubarMenu>
	);
}

// web/src/ui/menus/help.svelte
<script lang="ts">
    import { getContext } from "svelte";
    import { _ } from "svelte-i18n";
    import { Menubar, Dialog } from "bits-ui";
    import About from "../dialogs/about.svelte";
    import Updates from "../dialogs/updates.svelte";
    // import type { DialogState } from "../../store/dialog.svelte";

    // const dialog = getContext<DialogState>("dialog");

    function openAbout() {
        // dialog.setDialog(About);
    }

    function openUpdates() {
        // dialog.setDialog(Updates);
    }
</script>

<Menubar.Menu>
    <Menubar.Trigger>{$_("help.title", { default: "Help" })}</Menubar.Trigger>
    <Menubar.Content>
        <Dialog.Trigger asChild>
            <Menubar.Item on:click={openUpdates}>
                {$_("help.updates", { default: "Check for updates" })}
            </Menubar.Item>
        </Dialog.Trigger>
        <Menubar.Separator />
        <Dialogs.Trigger asChild>
            <Menubar.Item on:click={openAbout}>
                {$_("help.about", { default: "About" })}
            </Menubar.Item>
        </Dialogs.Trigger>
    </Menubar.Content>
</Menubar.Menu>
