// ui/src/ui/menus/language.tsx
import {
	MenubarContent,
	MenubarMenu,
	MenubarRadioGroup,
	MenubarRadioItem,
	MenubarTrigger,
} from "@/components/ui/menubar.tsx";
import { languages } from "@/lib/i18n.ts";
import { useConfigStore } from "@/lib/api.ts";
import { useTranslation } from "react-i18next";

export default function Language() {
	const { t } = useTranslation();
	const language = useConfigStore((s) => s.language);
	const setLanguage = useConfigStore((s) => s.setLanguage);

	return (
		<MenubarMenu>
			<MenubarTrigger>{t("language.title", "Language")}</MenubarTrigger>
			<MenubarContent>
				<MenubarRadioGroup
					value={language}
					onValueChange={(value) => setLanguage(value)}
				>
					{languages.map((language) => (
						<MenubarRadioItem key={language} value={language}>
							{t(`language.${language}`)}
						</MenubarRadioItem>
					))}
				</MenubarRadioGroup>
			</MenubarContent>
		</MenubarMenu>
	);
}

// web/src/ui/menus/language.svelte
<script lang="ts">
    import { getContext } from "svelte";
    import { _ } from "svelte-i18n";
    import { Menubar } from "bits-ui";
    import { languages } from "src/lib/api.svelte";
    import type { ConfigState } from "src/lib/api.svelte";

    const config = getContext<ConfigState>("config");

    function setLanguage(language: string) {
        config.locale = language;
    }
</script>

<Menubar.Menu>
    <Menubar.Trigger>{$_("language.title", { default: "Language" })}</Menubar.Trigger>
    <Menubar.Content>
        <Menubar.RadioGroup value={config.locale} on:change={(event) => setLanguage(event.detail)}>
            {#each languages as language}
                <Menubar.RadioItem key={language} value={language}>
                    {$_(`language.${language}`)}
                </Menubar.RadioItem>
            {/each}
        </Menubar.RadioGroup>
    </Menubar.Content>
</Menubar.Menu>
