// web/src/ui/menus/font.svelte
<script lang="ts">
    import { getContext } from "svelte";
    import { _ } from "svelte-i18n";
    import { Menubar } from "bits-ui";
    import type { ConfigState } from "src/lib/api.svelte";

    const config = getContext<ConfigState>("config");
</script>

<Menubar.Menu>
    <Menubar.Trigger>{$_("font.title", { default: "Font" })}</Menubar.Trigger>
    <Menubar.Content>
        <Menubar.Item on:click={config.increaseFontSize}>
            {$_("font.increase", { default: "Increase size" })}
        </Menubar.Item>
        <Menubar.Item on:click={config.decreaseFontSize}>
            {$_("font.decrease", { default: "Decrease size" })}
        </Menubar.Item>
        <Menubar.Item on:click={config.resetFontSize}>
            {$_("font.reset", { default: "Reset size" })}
        </Menubar.Item>
    </Menubar.Content>
</Menubar.Menu>

// ui/src/ui/menus/font.tsx
import { MenubarContent, MenubarItem, MenubarMenu, MenubarTrigger } from "@/components/ui/menubar.tsx";
import { useConfigStore } from "@/lib/api.ts";
import { useTranslation } from "react-i18next";

export default function Font() {
    const { t } = useTranslation();
    const increase = useConfigStore((s) => s.increaseFontSize);
    const decrease = useConfigStore((s) => s.decreaseFontSize);
    const reset = useConfigStore((s) => s.resetFontSize);

    return (
        <MenubarMenu>
            <MenubarTrigger>{t("font.title", "Font")}</MenubarTrigger>
            <MenubarContent>
                <MenubarItem onClick={increase}>{t("font.increase", "Increase size")}</MenubarItem>
                <MenubarItem onClick={decrease}>{t("font.decrease", "Decrease size")}</MenubarItem>
                <MenubarItem onClick={reset}>{t("font.reset", "Reset size")}</MenubarItem>
            </MenubarContent>
        </MenubarMenu>
    );
}
