// web/src/ui/menus/view.svelte
<script lang="ts">
    import {getContext} from "svelte";
    import {_} from "svelte-i18n";
    import {Menubar} from "bits-ui";
    import  {type UIState, Layout, View} from "../../state/ui.svelte";

    const ui = getContext<UIState>("ui");

    function setView(view: View) {
        ui.view = view;
    }

    function setLayout(layout: Layout) {
        ui.layout = layout;
    }
</script>

<Menubar.Menu>
    <Menubar.Trigger>{$_("view.title", {default: "View"})}</Menubar.Trigger>
    <Menubar.Content>
        <Menubar.Sub>
            <Menubar.SubTrigger>{$_("view.editors", {default: "Editors"})}</Menubar.SubTrigger>
            <Menubar.SubContent>
                <Menubar.RadioGroup value={ui.view} on:change={(event) => setView(event.detail)}>
                    <Menubar.RadioItem value={View.JSONAndGo}>
                        {$_("view.both", {default: "JSON and Go"})}
                    </Menubar.RadioItem>
                    <Menubar.RadioItem value={View.JSONOnly}>
                        {$_("view.jsonOnly", {default: "JSON"})}
                    </Menubar.RadioItem>
                    <Menubar.RadioItem value={View.GoOnly}>
                        {$_("view.goOnly", {default: "Go"})}
                    </Menubar.RadioItem>
                </Menubar.RadioGroup>
            </Menubar.SubContent>
        </Menubar.Sub>
        <Menubar.Sub>
            <Menubar.SubTrigger>{$_("view.layout", {default: "Layout"})}</Menubar.SubTrigger>
            <Menubar.SubContent>
                <Menubar.RadioGroup value={ui.layout} on:change={(event) => setLayout(event.detail)}>
                    <Menubar.RadioItem value={Layout.TwoColumns}>
                        {$_("view.columns", {default: "Two Columns"})}
                    </Menubar.RadioItem>
                    <Menubar.RadioItem value={Layout.TwoRows}>
                        {$_("view.rows", {default: "Two Rows"})}
                    </Menubar.RadioItem>
                </Menubar.RadioGroup>
            </Menubar.SubContent>
        </Menubar.Sub>
    </Menubar.Content>
</Menubar.Menu>

// ui/src/ui/menus/view.tsx
import {
	MenubarContent,
	MenubarMenu,
	MenubarRadioGroup,
	MenubarRadioItem,
	MenubarSub,
	MenubarSubContent,
	MenubarSubTrigger,
	MenubarTrigger,
} from "@/components/ui/menubar.tsx";
import { Layout, useLayoutStore } from "@/store/layout.ts";
import { View, useViewStore } from "@/store/view.ts";
import { useTranslation } from "react-i18next";

export default function ViewMenu() {
	const { t } = useTranslation();
	const { layout, setLayout } = useLayoutStore();
	const { view, setView } = useViewStore();

	return (
		<MenubarMenu>
			<MenubarTrigger>{t("view.title", "View")}</MenubarTrigger>
			<MenubarContent>
				<MenubarSub>
					<MenubarSubTrigger>{t("view.editors", "Editors")}</MenubarSubTrigger>
					<MenubarSubContent>
						<MenubarRadioGroup
							value={view}
							onValueChange={(value) => setView(value as View)}
						>
							<MenubarRadioItem value={View.JSONAndGo}>
								{t("view.both", View.JSONAndGo)}
							</MenubarRadioItem>
							<MenubarRadioItem value={View.JSONOnly}>
								{View.JSONOnly}
							</MenubarRadioItem>
							<MenubarRadioItem value={View.GoOnly}>
								{View.GoOnly}
							</MenubarRadioItem>
						</MenubarRadioGroup>
					</MenubarSubContent>
				</MenubarSub>
				<MenubarSub>
					<MenubarSubTrigger>{t("view.layout", "Layout")}</MenubarSubTrigger>
					<MenubarSubContent>
						<MenubarRadioGroup
							value={layout}
							onValueChange={(value) => setLayout(value as Layout)}
						>
							<MenubarRadioItem value={Layout.TwoColumns}>
								{t("view.columns", Layout.TwoColumns)}
							</MenubarRadioItem>
							<MenubarRadioItem value={Layout.TwoRows}>
								{t("view.rows", Layout.TwoRows)}
							</MenubarRadioItem>
						</MenubarRadioGroup>
					</MenubarSubContent>
				</MenubarSub>
			</MenubarContent>
		</MenubarMenu>
	);
}
