// app/ui/src/ui/updates.tsx
import {DialogClose, DialogContent, DialogFooter, DialogHeader, DialogTitle,} from "@/components/ui/dialog.tsx"
import {useEffect, useState} from "react"
import {GetLatestVersion, GetVersion} from "../../wailsjs/go/main/App"
import {Button} from "@/components/ui/button.tsx"
import {useTranslation} from "react-i18next"
import {OpenRelease} from "@/lib/utils.ts"

export default function () {
    const {t} = useTranslation()

    const [version, setVersion] = useState("")
    const [latestVersion, setLatestVersion] = useState("")
    const [message, setMessage] = useState(t("updates.checking", "Checking..."))

    useEffect(() => {
        Promise.all([GetVersion(), GetLatestVersion()]).then(
            ([version, latestVersion]) => {
                setVersion(version)
                setLatestVersion(latestVersion)
            }
        )

        if (!version || !latestVersion) {
            setMessage(t("updates.failed", "Unable to check for updates."))
            return
        }

        if (version === latestVersion) {
            setMessage(t("updates.none", "You are using the latest version."))
        } else {
            setMessage(`${t("updates.available", "A new version is available: ")}v${latestVersion}.`)
        }
    }, [])

    return (
        <DialogContent className="select-none">
            <DialogHeader>
                <DialogTitle>{t("updates.title", "Check for updates")}</DialogTitle>
            </DialogHeader>
            <p className="text-gray-900 leading-relaxed">{message}</p>
            <DialogFooter>
                {version && latestVersion && version !== latestVersion &&
                  <Button variant="secondary" onClick={() => OpenRelease(latestVersion)}>
                      {t("Download")}
                  </Button>
                }
                <DialogClose asChild>
                    <Button variant="secondary">{t("OK")}</Button>
                </DialogClose>
            </DialogFooter>
        </DialogContent>
    )
}

// web/src/ui/dialogs/updates.svelte
<script lang="ts">
    import {getContext} from "svelte";
    import {Button, Dialog} from "bits-ui";
    import {_} from "svelte-i18n";
    import type {ConfigState} from "../../lib/api.svelte";
    import {openRelease} from "../../lib/api.svelte";
    import {GetLatestVersion, GetVersion} from "../../../wailsjs/go/main/App";

    let config = getContext<ConfigState>("config");
    let version = $state("");
    let latestVersion = $state("");
    let message = $state("");
    let isChecking = $state(true);

    $effect(() => {
        Promise.all([GetVersion(), GetLatestVersion()]).then(
            ([version_, latestVersion_]) => {
                version = version_;
                latestVersion = latestVersion_;
                isChecking = false;
            },
        );
    })

    $effect(() => {
        if (isChecking) {
            message = $_("updates.checking", {default: "Checking..."});
        } else if (version && latestVersion && version === latestVersion) {
            message = $_("updates.latest", {default: "You are using the latest version."});
        } else if (version && latestVersion && version !== latestVersion) {
            message = $_("updates.new", {default: "A new version is available: "}) + `v${latestVersion}`;
        } else {
            message = $_("updates.failed", {default: "Unable to check for updates."});
        }
    })

</script>

<Dialog.Content class="select-none">
    <Dialog.Header>
        <Dialog.Title>{$_("updates.title", {default: "Check for updates"})}</Dialog.Title>
    </Dialog.Header>
    <p class="text-gray-900 leading-relaxed">{message}</p>
    <Dialog.Footer>
        {#if version && latestVersion && version !== latestVersion}
            <Button variant="secondary" on:click={() => openRelease(latestVersion)}>
                {$_("Download")}
            </Button>
        {/if}
        <Dialog.Close asChild>
            <Button variant="secondary">{$_("OK")}</Button>
        </Dialog.Close>
    </Dialog.Footer>
</Dialog.Content>
