// web/src/ui/container.svelte
<script lang="ts">
    import { getContext } from "svelte";
    import { Layout } from "../state/ui.svelte";
    import type { UIState } from "../state/ui.svelte";

    const ui = getContext<UIState>("ui");
</script>

<div class={`grid h-64 grow border-t border-b ${ui.layout === Layout.TwoColumns ? 'grid-cols-2' : ''} ${ui.layout === Layout.TwoRows ? 'grid-rows-2' : ''}`}>
    <slot></slot>
</div>

// json2go-web/src/ui/container.tsx
import { cn } from "@/lib/utils.ts";
import { Layout, useLayoutStore } from "@/store/layout.ts";
import type { PropsWithChildren } from "react";

export default function ({ children }: PropsWithChildren) {
	const layout = useLayoutStore((state) => state.layout);

	return (
		<div
			className={cn("grid h-64 grow border-t border-b", {
				"grid-cols-2": layout === Layout.TwoColumns,
				"grid-rows-2": layout === Layout.TwoRows,
			})}
		>
			{children}
		</div>
	);
}
